; Configuração para o desenvolvimento real na placa
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Configuração EXCLUSIVA para rodar os testes automatizados na CI (GitHub Actions)
[env:native]
platform = native
test_framework = unity