; =====================================================================
; CONFIGURAÇÃO GLOBAL DO PROJETO MICROMOUSE
; =====================================================================
[platformio]
default_envs = esp32doit-devkit-v1

; ---------------------------------------------------------------------
; Ambiente 1: Desenvolvimento Físico na Placa DevKit V1 (Bancada Local)
; ---------------------------------------------------------------------
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
; upload_speed = 115200
; build_src_filter = +<*> -<src/main.cpp> +<test/test_motores.cpp>

; 🔌 PORTAS USB LOCAIS: Comentadas para usar a varredura automática do PlatformIO.
; Se precisar travar em uma porta específica do Linux, mude o número e tire o ';'
; upload_port = /dev/ttyUSB1
; monitor_port = /dev/ttyUSB1

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3
    adafruit/Adafruit INA219@^1.2.3

; ---------------------------------------------------------------------
; Ambiente 2: Configuração EXCLUSIVA para Testes Automatizados na CI (GitHub Actions)
; ---------------------------------------------------------------------
[env:native]
platform = native
test_framework = unity