; =====================================================================
; CONFIGURAÇÃO GLOBAL DO PROJETO MICROMOUSE
; =====================================================================

; ---------------------------------------------------------------------
; Ambiente 1: Desenvolvimento Físico na Placa DevKit V1 (Bancada Local)
; ---------------------------------------------------------------------

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3
    adafruit/Adafruit INA219@^1.2.3

; ---------------------------------------------------------------------
; Ambiente 2: Configuração EXCLUSIVA para Testes Automatizados na CI (GitHub Actions)
; ---------------------------------------------------------------------
[env:native]
platform = native
test_framework = unity
