// aqui ficar o modelo geral dos pop-ups, recomendo fazer uma tela só, fazer com que os dados sejam tipados em title, description, options... fica melhor de estruturar, no caso ele receberia uma state informando qual seria o tipo de popup e com isso ele exibiria na tela... 

// tem q adicionar dentro do app.tsx o efeito blur e o popup para ser exibido no meio da tela...